//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetOpenData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FavoriteRecord = new HashSet<FavoriteRecord>();
            this.ScoreRecord = new HashSet<ScoreRecord>();
            this.SearchRecord = new HashSet<SearchRecord>();
        }
    
        public int user_ID { get; set; }
        public int user_FBID { get; set; }
        public string user_email { get; set; }
        public string user_tel { get; set; }
        public Nullable<System.DateTime> user_birth { get; set; }
        public string user_name { get; set; }
        public string user_other { get; set; }
    
        public virtual ICollection<FavoriteRecord> FavoriteRecord { get; set; }
        public virtual ICollection<ScoreRecord> ScoreRecord { get; set; }
        public virtual ICollection<SearchRecord> SearchRecord { get; set; }
    }
}
