//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiSee_v1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Area
    {
        public Area()
        {
            this.Spot = new HashSet<Spot>();
        }

        [Display(Name = "ID")]
        public int area_ID { get; set; }
        [Display(Name = "區域")]
        public string area_Name { get; set; }

        public virtual ICollection<Spot> Spot { get; set; }
    }
}
