//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiSee_v1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CommentRecord
    {
        [Display(Name = "ID")]
        public int commentrecord_ID { get; set; }
        [Display(Name = "景點")]
        public int spot_ID { get; set; }
        [Display(Name = "會員")]
        public int user_ID { get; set; }
        [Display(Name = "評論")]
        public string comment_context { get; set; }
        public string comment_grade { get; set; }
        [Display(Name = "評論時間")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> comment_date { get; set; }

        public virtual Spot Spot { get; set; }
        public virtual User User { get; set; }
    }
}
