//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiSee_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spot
    {
        public Spot()
        {
            this.FavoriteRecord = new HashSet<FavoriteRecord>();
            this.ScoreRecord = new HashSet<ScoreRecord>();
            this.SearchRecord = new HashSet<SearchRecord>();
        }
    
        public int spot_ID { get; set; }
        public int area_ID { get; set; }
        public string spot_name { get; set; }
        public string spot_tel { get; set; }
        public string spot_context { get; set; }
        public Nullable<System.TimeSpan> spot_optimeS { get; set; }
        public Nullable<System.TimeSpan> spot_optimeE { get; set; }
        public string spot_add { get; set; }
        public string spot_fee { get; set; }
        public string spot_score { get; set; }
        public string spot_other { get; set; }
        public int class_ID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Class Class { get; set; }
        public virtual ICollection<FavoriteRecord> FavoriteRecord { get; set; }
        public virtual ICollection<ScoreRecord> ScoreRecord { get; set; }
        public virtual ICollection<SearchRecord> SearchRecord { get; set; }
    }
}
