//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiSee_v1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Spot
    {
        public Spot()
        {
            this.FavoriteRecord = new HashSet<FavoriteRecord>();
            this.ScoreRecord = new HashSet<ScoreRecord>();
            this.SearchRecord = new HashSet<SearchRecord>();
        }

        [Display(Name = "ID")]
        public int spot_ID { get; set; }
        [Display(Name = "地區")]
        public int area_ID { get; set; }

        [Required]
        [Display(Name = "名稱")]
        public string spot_name { get; set; }
        [Display(Name = "連絡電話")]
        public string spot_tel { get; set; }
        [Display(Name = "介紹")]
        public string spot_context { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "營業時間起時")]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.TimeSpan> spot_optimeS { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "營業時間訖時")]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.TimeSpan> spot_optimeE { get; set; }
        [Display(Name = "地址")]
        public string spot_add { get; set; }
        [Display(Name = "門票")]
        public string spot_fee { get; set; }
        [Display(Name = "評分")]
        public string spot_score { get; set; }
        [Display(Name = "其他")]
        public string spot_other { get; set; }
        [Display(Name = "類型")]
        public int class_ID { get; set; }

        public virtual Area Area { get; set; }
        public virtual Class Class { get; set; }
        public virtual ICollection<FavoriteRecord> FavoriteRecord { get; set; }
        public virtual ICollection<ScoreRecord> ScoreRecord { get; set; }
        public virtual ICollection<SearchRecord> SearchRecord { get; set; }
    }
}
